assetmanagement:
  indexfile_location: "bpmtree/indexdata/assetmanagement/embedded.pkl"
  treefile_location: "bpmtree/treedata/assetmanagement/businesscontext.csv"
banking:
  indexfile_location: "bpmtree/indexdata/banking/embedded.pkl"
  treefile_location: "bpmtree/treedata/banking/businesscontext.csv"
healthcareinsurance:
  indexfile_location: "bpmtree/indexdata/healthcareinsurance/embedded.pkl"
  treefile_location: "bpmtree/treedata/healthcareinsurance/businesscontext.csv"
capitalmarkets:
…  treefile_location: "bpmtree/treedata/retail/businesscontext.csv"
retailecommerce:
  indexfile_location: "bpmtree/indexdata/retailecommerce/embedded.pkl"
  treefile_location: "bpmtree/treedata/retailecommerce/businesscontext.csv"
travelaviationairlines:
  indexfile_location: "bpmtree/indexdata/travelaviationairlines/embedded.pkl"
  treefile_location: "bpmtree/treedata/travelaviationairlines/businesscontext.csv"
